
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


env = PATH,$PATH:$HOME/bin:$HOME/.local/share/omarchy/bin
#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    # follow_mouse = 1
    # sensitivity = 0
    # force_no_accel = 0
    # accel_profile = flat 
    # numlock_by_default = true

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = no
    }
    # kb_options = altwin:swap_alt_win

}


# 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures
gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
}

# for window shallow similar to devour
misc {
    # enable_swallow = true
    # swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
}

# Don't show update on first launch
ecosystem {
  # no_update_news = true
}

general {
  gaps_in = 1
  gaps_out = 1
  border_size = 2
  allow_tearing = true
}

decoration {
  active_opacity = 1
  inactive_opacity = 1
}

animations {
  enabled = true
}

plugin {
  hyprfocus {
    enabled = yes
    animate_floating = no
    animate_workspacechange = no
    focus_animation = shrink
      # Beziers for focus animations
    bezier = bezIn, 0.5, 0.0, 1.0, 0.5
    bezier = bezOut, 0.0, 0.5, 0.5, 1.0
    bezier = overshot, 0.05, 0.9, 0.1, 1.05
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = smoothIn, 0.25, 1, 0.5, 1
    bezier = realsmooth, 0.28, 0.29, 0.69, 1.08
    bezier = easeInOutBack, 0.68, -0.6, 0.32, 1.6
      # Flash settings
    flash {
      flash_opacity = 0.7
      in_bezier = bezIn
      in_speed = 0.5
      out_bezier = bezOut
      out_speed = 3
    }
      # Shrink settings
    shrink {
      shrink_percentage = 0.99
      in_bezier = easeInOutBack
      in_speed = 1.5
      out_bezier = easeInOutBack
      out_speed = 3
    }
  }
}

workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
windowrulev2 = rounding 0, floating:0, onworkspace:f[1]
