
[Wallbash]
text               = FFE7CC
subtext            = F0CFAA
nav-active-text    = E6C29A
main               = 111126
sidebar            = 111126
player             = 111126
card               = 111126
shadow             = 292952
main-secondary     = 3A506B
button             = F0AFAA
button-secondary   = E69F9A
button-active      = C27F7A
button-disabled    = 20426D
nav-active         = 6B3D3A
play-button        = 7D4F4B
tab-active         = 20426D
notification       = 111126
notification-error = 111126
playback-bar       = 111126
misc               = 20426D

; Description

; text             = main text, playlist names in main field, name of playlist selected in sidebar, headings
; subtext          = text in main buttons in sidebar, playlist names in sidebar, artist names, and mini infos
; nav-active-text  = text in main buttons in sidebar when active
; main             = main bg
; main-secondary   = bg color of selected song rows, bg color of artist/track cards
; sidebar          = sidebar bg
; player           = player bg
; card             = popup-card bg
; shadow           = all shadows
; button           = playlist buttons bg in sidebar, drop-down menus, now playing song, like button
; button-secondary = download and options button
; button-active    = hover on song selected
; button-disabled  = seekbar bg, volume bar bg, scrollbar
; nav-active       = sidebar buttons bg
; play-button      = color of main play button in main field
; tab-active       = button bg in main field (playlists, podcasts, artists, albums)
; notification     = notification ('Added to liked songs' etc.)
; playback-bar     = seekbar fg, volume bar fg, main play/pause button
; misc             = miscellaneous
