
[Wallbash]
text               = CCFDFF
subtext            = AAEDF0
nav-active-text    = 9AE2E6
main               = 182D2F
sidebar            = 182D2F
player             = 182D2F
card               = 182D2F
shadow             = 294E52
main-secondary     = 3A6A6B
button             = AAF0EE
button-secondary   = 9AE6E3
button-active      = 7AC2C0
button-disabled    = 366263
nav-active         = 3A6B6A
play-button        = 4B7D7B
tab-active         = 366263
notification       = 182D2F
notification-error = 182D2F
playback-bar       = 182D2F
misc               = 366263

; Description

; text             = main text, playlist names in main field, name of playlist selected in sidebar, headings
; subtext          = text in main buttons in sidebar, playlist names in sidebar, artist names, and mini infos
; nav-active-text  = text in main buttons in sidebar when active
; main             = main bg
; main-secondary   = bg color of selected song rows, bg color of artist/track cards
; sidebar          = sidebar bg
; player           = player bg
; card             = popup-card bg
; shadow           = all shadows
; button           = playlist buttons bg in sidebar, drop-down menus, now playing song, like button
; button-secondary = download and options button
; button-active    = hover on song selected
; button-disabled  = seekbar bg, volume bar bg, scrollbar
; nav-active       = sidebar buttons bg
; play-button      = color of main play button in main field
; tab-active       = button bg in main field (playlists, podcasts, artists, albums)
; notification     = notification ('Added to liked songs' etc.)
; playback-bar     = seekbar fg, volume bar fg, main play/pause button
; misc             = miscellaneous
