[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[plugin]
prepend_preloaders = [
  # Office Documents
  { mime = "application/openxmlformats-officedocument.*", run = "office" },
  { mime = "application/oasis.opendocument.*", run = "office" },
  { mime = "application/ms-*", run = "office" },
  { mime = "application/msword", run = "office" },
  { name = "*.docx", run = "office" },
]

prepend_previewers = [
  # Office Documents
  { mime = "application/openxmlformats-officedocument.*", run = "office" },
  { mime = "application/oasis.opendocument.*", run = "office" },
  { mime = "application/ms-*", run = "office" },
  { mime = "application/msword", run = "office" },
  { name = "*.docx", run = "office" },
  { mime = "application/epub+zip", run = "epub-preview" },
  { name = "*.csv", run = 'piper -- bat -p --color=always "$1"' },
  { mime = "text/*", run = 'piper -- bat -p --color=always "$1"' },
  { mime = "*/xml", run = 'piper -- bat -p --color=always "$1"' },
  { mime = "*/cs", run = 'piper -- bat -p --color=always "$1"' },
  { mime = "*/javascript", run = 'piper -- bat -p --color=always "$1"' },
  { mime = "*/x-wine-extension-ini", run = 'piper -- bat -p --color=always "$1"' },
  { url = "*.tar*", run = 'piper --format=url -- tar tf "$1"' },
  { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
  { url = "*/", run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"' },
]
[opener]
open = [{ run = 'ghostty -e lue "$@"' }]

[open]
prepend_rules = [{ name = "*.epub", use = 'open' }]

[mgr]
show_hidden = true
ratio = [1, 2, 5]
